.PHONY: clean All

All:
	@echo "----------Building project:[ HappyVM - Debug ]----------"
	@cd "HappyVM" && "$(MAKE)" -f  "HappyVM.mk"
clean:
	@echo "----------Cleaning project:[ HappyVM - Debug ]----------"
	@cd "HappyVM" && "$(MAKE)" -f  "HappyVM.mk" clean
